For the most part timekpr works on whole exact seconds, which should   be of data type int, however there were some calculations using   total_seconds(), which return float, thus int + float = float.
This was not a big deal, albeit a little not right from coding
  style perspective (there were always rounded seconds due to
  discard of microsec) and python dynamic types don't help either
  , but it worked like a charm until something changed.

Due to some change in latest python or python dbus interaction or
  some other unknown thing, dbus method calls from python which
  expect int, but instead get float, started to fail with errors
  like this:
==========
... in emit_signal
  message.append(signature=signature, *args)
  TypeError: 'float' object cannot be interpreted as an integer
=========

This fix converts all seconds calculations to int which solves
  the issue.